






---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ----------
  labels:
    app: ---------- 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ------------
  template:
    metadata:
      labels:
        app: --------
    spec:
      containers:
        - name: ------------
          image: ---------
          ports:
            - containerPort: 
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
            env:
              - name: MYSQL_DATABASE
                value: drupal
              - name: MYSQL_USER
                value: user
              - name: MYSQL_PASSWORD
                value: password
              - name: MYSQL_ROOT_PASSWORD
                value: password
